### ISSUE TITLE
Editorial: clarify the use of L, P, M, etc

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-loc#15]
Sometimes the letters are limited for use in examples:

>  “The example PWP in this document is denoted P.”

Other times they seem to be used in replacement for the concepts:

> “Throughout the document, we will use L as the canonical locator of a published PWP. ”

I would suggest that:
- all general “spec-level” statements are written with the explicit terms
- letters are only used for examples

Generally, I find that letters are convenient shorthand for our internal discussions, but IMHO they make the document harder to read for newcomers (as they add another level of abstraction to what is already very abstract).

**Comment by TzviyaSiegman** [comment]
+1000

**Comment by rdeltour** [comment]
IMHO there are still places where we should use the explicit terms, notably when we talk about Lu and Lp.  For instance, some instances of “**Lu** and **Lp**” could be replaced by "**state dependent locators**", some instances of "**L**" by "**canonical locator**", etc.

**Comment by bjdmeest** [comment]
Proposal: remove all **L**\* except for in http://w3c.github.io/dpub-pwp-loc/#algorithm-to-find-the-right-values-for-lp-and-lu, and define them there.

**Comment by rdeltour** [comment]
> Proposal: remove all L\* except for in http://w3c.github.io/dpub-pwp-loc/#algorithm-to-find-the-right-values-for-lp-and-lu, and define them there.

Sounds good to me (but maybe ask to the larger group during our call?)

**Comment by iherman** [comment]
I found the radical approach of @bjdmeest a bit too radical, when reading through the text; the terminology section does have some places (e.g., the combination of manifests) which read better (in my view) if the more "mathematical" notation is used. Nevertheless, I tried to use the English term instead of the abbreviated form at a number of places, primarily in the terminology section. See PR #26 for details.
